modLoader = "javafml"
loaderVersion = "[0,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "openlink_frpc_api"
version = "1.0.0"
displayName = "OpenLink Frpc API"
authors = "Terry_MC"
description = '''
'''
logoFile = "icon.png"

[[dependencies.openlink_frpc_api]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openlink_frpc_api]]
modId = "minecraft"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"